# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "dandyrilla"

author:
  facebook:         dandyrilla
  youtubeUser:      
  youtubeChannel:   
  twitter:          
  github:           dandyrilla
  stackoverflow:    
  quora:            
  linkedin:         
  pinterest:        
  googlePlus:       
  instagram:        
  reddit:           
  medium:           
  tumblr:           
  email:            dandyrilla@naver.com

copyright:
  year:             2019
  name:             dandyrilla

# Google-analytics
google-analytics:
  id:               "UA-126097508-1"

# Disqus
disqus:
  id:               "dandyrilla"

# URL
url:                "https://dandyrilla.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           10
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/dandyrilla"
  - name:           "Links"
    url:            "/links"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
